POST http://localhost:3000/reports
Content-Type: application/json

{
  "make":"Toyota",
  "model":"Camry",
  "year":2022,
  "mileage":100,
  "lng": 0,
  "lat": 0,
  "price": 250000
}

### Approve an existing report
PATCH http://localhost:3000/reports/2
Content-Type: application/json

{"approved": true}

### Get an estimate for an existing vehicle
GET http://localhost:3000/reports?make=Toyota&model=corolla&lng=0&lat=0&mileage=2025&year=2000
